//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.11 at 10:59:48 PM CEST 
//


package com.zahtev.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.zahtev.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.zahtev.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAcceptResponse }
     * 
     */
    public GetAcceptResponse createGetAcceptResponse() {
        return new GetAcceptResponse();
    }

    /**
     * Create an instance of {@link NewIzvestajResponse }
     * 
     */
    public NewIzvestajResponse createNewIzvestajResponse() {
        return new NewIzvestajResponse();
    }

    /**
     * Create an instance of {@link GetIzvestajResponse }
     * 
     */
    public GetIzvestajResponse createGetIzvestajResponse() {
        return new GetIzvestajResponse();
    }

    /**
     * Create an instance of {@link BundleRequests }
     * 
     */
    public BundleRequests createBundleRequests() {
        return new BundleRequests();
    }

    /**
     * Create an instance of {@link GetAcceptRequest }
     * 
     */
    public GetAcceptRequest createGetAcceptRequest() {
        return new GetAcceptRequest();
    }

    /**
     * Create an instance of {@link NewIzvestajRequest }
     * 
     */
    public NewIzvestajRequest createNewIzvestajRequest() {
        return new NewIzvestajRequest();
    }

    /**
     * Create an instance of {@link Izvestaj }
     * 
     */
    public Izvestaj createIzvestaj() {
        return new Izvestaj();
    }

    /**
     * Create an instance of {@link GetZahteviRequest }
     * 
     */
    public GetZahteviRequest createGetZahteviRequest() {
        return new GetZahteviRequest();
    }

    /**
     * Create an instance of {@link GetIzvestajIdRequest }
     * 
     */
    public GetIzvestajIdRequest createGetIzvestajIdRequest() {
        return new GetIzvestajIdRequest();
    }

    /**
     * Create an instance of {@link GetBundleIdRequest }
     * 
     */
    public GetBundleIdRequest createGetBundleIdRequest() {
        return new GetBundleIdRequest();
    }

    /**
     * Create an instance of {@link GetIzvestajIDResponse }
     * 
     */
    public GetIzvestajIDResponse createGetIzvestajIDResponse() {
        return new GetIzvestajIDResponse();
    }

    /**
     * Create an instance of {@link GetBundleIDResponse }
     * 
     */
    public GetBundleIDResponse createGetBundleIDResponse() {
        return new GetBundleIDResponse();
    }

    /**
     * Create an instance of {@link GetIzvestajRequest }
     * 
     */
    public GetIzvestajRequest createGetIzvestajRequest() {
        return new GetIzvestajRequest();
    }

    /**
     * Create an instance of {@link GetZahteviResponse }
     * 
     */
    public GetZahteviResponse createGetZahteviResponse() {
        return new GetZahteviResponse();
    }

    /**
     * Create an instance of {@link Zahtev }
     * 
     */
    public Zahtev createZahtev() {
        return new Zahtev();
    }

    /**
     * Create an instance of {@link Oglas }
     * 
     */
    public Oglas createOglas() {
        return new Oglas();
    }

    /**
     * Create an instance of {@link Vozilo }
     * 
     */
    public Vozilo createVozilo() {
        return new Vozilo();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

}
