version: '3.7'
services:

  servisi-front:
    build: ./ServisiFront
    container_name: serversFront
    restart: on-failure
    ports:
      - "4200:4200"
    networks:
      - xml

  eureka-serviceregistry:
    build: ./Servisi/EurekaServer
    container_name: eurekaServerRegistry
    restart: on-failure
    networks:
      - xml
    ports:
      - "8761:8761"

  eureka-oglas-service:
    build: ./Servisi/OglasService
    container_name: eurekaOglasService
    restart: on-failure
    networks:
      - xml
    ports:
      - "8092:8092"
    links:
      - postgresql-oglas
    environment:
      REGISTRY_HOST: eureka-serviceregistry
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: root
      DATABASE_DOMAIN: postgresql-oglas
      DATABASE_SCHEMA: oglas
    depends_on:
      - eureka-serviceregistry

  postgresql-oglas:
    image: postgres
    container_name: postgresql-oglas
    restart: always
    networks:
      - xml
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: oglas
    ports:
      - 5432:5432

  gateway-service:
    build: ./Servisi/GatewayService
    container_name: gatewayService
    restart: on-failure
    networks:
      - xml
    ports:
      - "8662:8662"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    depends_on:
      - eureka-serviceregistry
      - eureka-oglas-service

networks:
  xml:
    name: xml
    driver: bridge
