package com.authorization.authorizationService.model;

public enum RoleEnum {
	ROLE_USER,ROLE_AGENT,ROLE_ADMIN,OGLAS_READ, OGLAS_WRITE,KORISNIK_READ,KORISNIK_WRITE,VOZILO_READ,VOZILO_WRITE,
	SLIKA_READ,SLIKA_WRITE,MODEL_READ,MODEL_WRITE,MARKA_READ,MARKA_WRITE,TIPGORIVA_READ,
	TIPGORIVA_WRITE,MENJAC_READ,MENJAC_WRITE,KLASA_READ,KLASA_WRITE,ZAHTEV_READ,ZAHTEV_WRITE

}
